import re

DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "Technology": [
        "ai",
        "crypto",
        "social media",
        "tech",
        "internet",
        "software",
        "robot",
        "algorithm",
        "digital",
        "blockchain",
        "data",
        "chatgpt",
        "engineer",
        "autonomous",
        "surveillance",
        "machine learning",
        "automation",
        "quantum",
        "computer",
        "coding",
        "app",
        "platform",
        "smartphone",
        "virtual reality",
        "augmented reality",
        "metaverse",
    ],
    "Politics": [
        "government",
        "policy",
        "law",
        "democracy",
        "election",
        "military",
        "immigration",
        "tax",
        "war",
        "president",
        "congress",
        "vote",
        "sanction",
        "partisan",
        "senate",
        "constitution",
        "diplomacy",
        "politician",
        "republic",
        "socialist",
        "libertarian",
        "bureaucracy",
        "referendum",
        "parliament",
        "regime",
        "authoritarian",
        "coup",
    ],
    "Society": [
        "education",
        "social",
        "culture",
        "community",
        "inequality",
        "family",
        "gender",
        "race",
        "religion",
        "crime",
        "prison",
        "poverty",
        "diversity",
        "homeless",
        "drug",
        "marriage",
        "tradition",
        "protest",
        "feminism",
        "racism",
        "discrimination",
        "privilege",
        "identity",
        "class",
        "school",
        "university",
        "parenting",
        "aging",
        "youth",
        "migration",
    ],
    "Health": [
        "health",
        "medicine",
        "vaccine",
        "mental",
        "fitness",
        "food",
        "pandemic",
        "hospital",
        "obesity",
        "nutrition",
        "medicare",
        "cancer",
        "surgery",
        "therapy",
        "pharmaceutical",
        "drug addiction",
        "doctor",
        "patient",
        "disease",
        "disorder",
        "diet",
        "exercise",
        "wellbeing",
        "addiction",
        "smoking",
        "alcohol",
        "opioid",
    ],
    "Business": [
        "economy",
        "market",
        "trade",
        "business",
        "finance",
        "corporate",
        "startup",
        "job",
        "salary",
        "inflation",
        "stock",
        "minimum wage",
        "union",
        "gdp",
        "investment",
        "monopoly",
        "capitalism",
        "entrepreneur",
        "profit",
        "revenue",
        "bankrupt",
        "recession",
        "wealth",
        "income",
        "outsourcing",
        "remote work",
        "gig economy",
    ],
    "Energy & Climate": [
        "climate",
        "energy",
        "nuclear",
        "carbon",
        "environment",
        "fossil",
        "renewable",
        "pollution",
        "solar",
        "oil",
        "electric vehicle",
        "green",
        "emission",
        "paris",
        "wind power",
        "sustainability",
        "global warming",
        "deforestation",
        "plastic",
        "recycling",
        "biodiversity",
        "ecosystem",
        "drought",
        "flood",
        "wildfire",
        "sea level",
    ],
    "Arts & Media": [
        "media",
        "film",
        "art",
        "music",
        "entertainment",
        "journalism",
        "censorship",
        "streaming",
        "book",
        "copyright",
        "hollywood",
        "news",
        "influencer",
        "podcast",
        "video game",
        "advertising",
        "literature",
        "theatre",
        "photography",
        "dance",
        "social media",
        "press freedom",
        "fake news",
        "propaganda",
        "celebrity",
    ],
    "Sports": [
        "sport",
        "athlete",
        "football",
        "soccer",
        "basketball",
        "baseball",
        "tennis",
        "chess",
        "olympic",
        "esport",
        "gaming",
        "cricket",
        "rugby",
        "swimming",
        "marathon",
        "doping",
        "stadium",
        "league",
        "champion",
        "tournament",
        "coach",
        "referee",
        "fan",
        "spectator",
    ],
    "Philosophy & Ethics": [
        "ethic",
        "moral",
        "philosophy",
        "justice",
        "freedom",
        "liberty",
        "consciousness",
        "meaning",
        "existence",
        "truth",
        "rights",
        "duty",
        "virtue",
        "free will",
        "determinism",
        "utilitarianism",
        "deontology",
        "equality",
        "fairness",
        "dignity",
        "autonomy",
    ],
    "Science": [
        "science",
        "research",
        "space",
        "universe",
        "evolution",
        "genetic",
        "biology",
        "chemistry",
        "physics",
        "astronomy",
        "experiment",
        "discovery",
        "species",
        "dna",
        "stem cell",
        "gene editing",
        "mars",
        "telescope",
        "particle",
        "theory",
        "hypothesis",
    ],
}

_STOPWORDS = frozenset(
    {
        "should",
        "would",
        "could",
        "can",
        "will",
        "is",
        "are",
        "was",
        "were",
        "be",
        "been",
        "the",
        "a",
        "an",
        "and",
        "or",
        "but",
        "for",
        "to",
        "in",
        "of",
        "on",
        "at",
        "by",
        "from",
        "with",
        "about",
        "that",
        "this",
        "it",
        "more",
        "less",
        "better",
        "worse",
        "good",
        "bad",
        "make",
        "makes",
        "have",
        "has",
        "do",
        "does",
        "did",
        "not",
        "no",
        "yes",
        "any",
        "all",
        "than",
        "then",
        "when",
        "where",
        "what",
        "who",
        "how",
        "why",
        "which",
        "its",
        "our",
        "their",
        "your",
        "they",
        "you",
        "ever",
        "always",
        "never",
        "every",
        "each",
        "both",
        "much",
        "many",
        "most",
        "some",
        "very",
        "just",
        "really",
        "truly",
        "actually",
        "basically",
        "generally",
        "overall",
        "replace",
        "become",
        "used",
        "using",
        "even",
        "still",
        "already",
        "world",
        "global",
        "modern",
        "today",
        "future",
        "human",
        "people",
        "society",
        "country",
        "nation",
        "government",
    }
)


def _extract_fallback_domain(topic: str) -> str:
    """Extract the most meaningful word from an unmatched topic to use as domain name."""
    words = re.findall(r"\b[a-zA-Z]{4,}\b", topic)
    for word in words:
        if word.lower() not in _STOPWORDS:
            return word.capitalize()
    return topic.split()[0].capitalize() if topic.split() else "Other"


def classify_topic(topic: str) -> tuple[str, list[str]]:
    """Returns (primary_domain, all_matched_domains). Primary is highest-scoring.
    If no domain matches, derives a meaningful label from the topic text itself."""
    lower = topic.lower()
    scores = {
        domain: sum(1 for kw in keywords if kw in lower)
        for domain, keywords in DOMAIN_KEYWORDS.items()
    }
    matched = sorted(
        [d for d, s in scores.items() if s > 0],
        key=lambda d: scores[d],
        reverse=True,
    )
    if not matched:
        fallback = _extract_fallback_domain(topic)
        return fallback, [fallback]
    return matched[0], matched
