DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "Technology": [
        "ai",
        "crypto",
        "social media",
        "tech",
        "internet",
        "software",
        "robot",
        "algorithm",
        "digital",
        "blockchain",
        "data",
        "chatgpt",
        "engineer",
        "autonomous",
        "surveillance",
        "machine learning",
        "automation",
    ],
    "Politics": [
        "government",
        "policy",
        "law",
        "democracy",
        "election",
        "military",
        "immigration",
        "tax",
        "war",
        "president",
        "congress",
        "vote",
        "sanction",
        "partisan",
        "senate",
        "constitution",
        "diplomacy",
    ],
    "Society": [
        "education",
        "social",
        "culture",
        "community",
        "inequality",
        "family",
        "gender",
        "race",
        "religion",
        "crime",
        "prison",
        "poverty",
        "diversity",
        "homeless",
        "drug",
        "marriage",
        "tradition",
        "protest",
    ],
    "Health": [
        "health",
        "medicine",
        "vaccine",
        "mental",
        "fitness",
        "food",
        "pandemic",
        "hospital",
        "obesity",
        "nutrition",
        "medicare",
        "cancer",
        "surgery",
        "therapy",
        "pharmaceutical",
        "drug addiction",
    ],
    "Business": [
        "economy",
        "market",
        "trade",
        "business",
        "finance",
        "corporate",
        "startup",
        "job",
        "salary",
        "inflation",
        "stock",
        "minimum wage",
        "union",
        "gdp",
        "investment",
        "monopoly",
        "capitalism",
    ],
    "Energy & Climate": [
        "climate",
        "energy",
        "nuclear",
        "carbon",
        "environment",
        "fossil",
        "renewable",
        "pollution",
        "solar",
        "oil",
        "electric vehicle",
        "green",
        "emission",
        "paris",
        "wind power",
        "sustainability",
    ],
    "Arts & Media": [
        "media",
        "film",
        "art",
        "music",
        "entertainment",
        "journalism",
        "censorship",
        "streaming",
        "book",
        "copyright",
        "hollywood",
        "news",
        "influencer",
        "podcast",
        "video game",
        "advertising",
    ],
}


def classify_topic(topic: str) -> str:
    lower = topic.lower()
    scores = {
        domain: sum(1 for kw in keywords if kw in lower)
        for domain, keywords in DOMAIN_KEYWORDS.items()
    }
    best = max(scores, key=scores.get)
    return best if scores[best] > 0 else "General"
